var express    = require('express');        
var app        = express();                 
var bodyParser = require('body-parser');
var path = require('path');

// configure app to use bodyParser()
// this will let us get the data from a POST
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

var port = process.env.PORT || 9090;       
var router = express.Router();       
var database = new Array();

// views folder generated by angular with ng build
app.use('/', express.static('views'));

// api test (ttp://localhost:9090/comment/search)
router.get('/comment/search', function(req, res) {
    res.json(database);   
});

// api test (ttp://localhost:9090/api/comment)
router.route('/comment').post(function(req, res) {
    database.push({"Description": req.body.Description});
    res.json(req.body);
});

// all of our routes will be prefixed with /api
app.use('/api', router);

// start server
app.listen(port);
console.log('Server started at ' + port);