var express    = require('express');        
var app        = express();                 
var bodyParser = require('body-parser');
var path = require('path');


// configure app to use bodyParser()
// this will let us get the data from a POST
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

var port = process.env.PORT || 9090;       

var router = express.Router();       

// app.get('/', function(req, res) {
//     res.sendfile(path.join(__dirname + '/views/index.html'));
// });

// views folder generated by angular with ng build
app.use('/', express.static('views'));


var database = new Array();
database.push({"Description":"first comment"});
database.push({"Description":"second commencçt"});
database.push({"Description":"third comment"});

// api test (ttp://localhost:9090/comment/search)
router.get('/comment/search', function(req, res) {
    res.json(database);   
});

// api test (ttp://localhost:9090/api/comment)
router.route('/comment').post(function(req, res) {
    database.push({"Description": req.body.Description});
    console.log(req.body)
    res.json(req.body);
});

// all of our routes will be prefixed with /api
app.use('/api', router);

// start server
app.listen(port);
console.log('Server started at ' + port);