var express    = require('express');        
var app        = express();                 
var bodyParser = require('body-parser');
var path = require('path');

// configure app to use bodyParser()
// this will let us get the data from a POST
//app.use(bodyParser.urlencoded({ extended: true }));
//app.use(bodyParser.json());

var port = process.env.PORT || 8080;       

var router = express.Router();       

// app.get('/', function(req, res) {
//     res.sendfile(path.join(__dirname + '/views/index.html'));
// });

// views folder generated by angular with ng build
app.use('/', express.static('views'));

// api test (ttp://localhost:8080/api/get)
router.get('/get', function(req, res) {
    res.json({ message: 'hooray! welcome to our api!' });   
});

// all of our routes will be prefixed with /api
app.use('/api', router);

// start server
app.listen(port);
console.log('Server started at ' + port);